### ISSUE TITLE
Tests of energy on forces do not work for any code

### ISSUE THREAD

**Issue by gtribello** [plumed-testcenter/plumed-testcenter#3]
I am testing the PLUMED + MD code interface using the tests described here:

https://www.plumed.org/doc-v2.8/developer-doc/html/_how_to_plumed_your_m_d.html

The last of these tests (the one on the forces on the energy) does not work for any MD code and I cannot work out why.  If you look in runtests.py you can see how the calculations are setup.  When I had the tests on the interface with LAMMPS a few years ago I set the SLOPE parameter in plumed to 0.21 as opposed to 0.1 as it should be according to the instructions in the PLUMED manual.  I think that worked but I have no idea why I set SLOPE to that value.

**Comment by GiovanniBussi** [comment]
@gtribello there's some mistake in the formulas. Assuming we have a slope `alpha-1`, so that energy function is multiplied times `alpha`:
- Temperature should also be multiplied times `alpha`. Indeed, double energy function and double temperature should not change anything in the equilibrium distribution.
- Time units should be divided times `sqrt(alpha)`. Indeed, as T has been multiplied by `alpha`, velocities in the Boltzmann distribution will be multiplied by `sqrt(alpha)`. Thus, to have the same displacement (`=velocity X timestep`), you should divide timestep by the same amount.
- Friction follows the inverse rule since its units are inverse time units.

Below a working version:

```python
import subprocess
import numpy as np
tstep=0.005
friction=1.0
temperature=0.5

def run(name,alpha):

  with open("plumed.dat","w") as f:
   print(f"""
    e: ENERGY
    PRINT STRIDE=40 ARG=e FILE={name}
    RESTRAINT ARG=e AT=0.0 SLOPE={alpha-1}
    """,file=f)
  with open("in","w") as f:
   print(f"""\
    inputfile crystal.xyz
    outputfile output.xyz
    temperature {temperature*alpha}
    tstep {tstep/np.sqrt(alpha)}
    friction {friction*np.sqrt(alpha)}
    forcecutoff 2.5
    listcutoff  3.0
    nstep 200
    nconfig 10 trajectory.xyz
    nstat   10 energies.dat\
    """,file=f)
  subprocess.run(["plumed","simplemd","in"],check=True)

run("energy1",alpha=1.0)
run("energy2",alpha=1.1)

ene1=np.loadtxt("energy1").T
ene2=np.loadtxt("energy2").T

print()
print("Time is expected to be different")
for i in range(len(ene1[0])):
  print(ene1[0][i],ene2[0][i])

print()
print("Energy is expected to be the same")
for i in range(len(ene1[1])):
  print(ene1[1][i],ene2[1][i])
```

**Comment by gtribello** [comment]
Thanks for this information @GiovanniBussi 

I have incorporated your suggestions and if you look now:

https://plumed-testcenter.github.io/browse.html

We at least have all green badges for simplemd.  Yay!

Resolving this impasse is great.  It now makes sense to try to see if we can also get some passes here for the other MD codes.

Thanks again.
